name: snapshot
base: core22
adopt-info: snapshot
grade: stable
confinement: strict

layout:
  /usr/share/snapshot:
    symlink: $SNAP/usr/share/snapshot

parts:    
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  pipewire:
    source: https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/0.3.79/pipewire-0.3.79.tar.gz
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Dalsa=disabled
      - -Dpipewire-alsa=disabled
      - -Djack=disabled
      - -Dpipewire-jack=disabled
      - -Dsession-managers=[]
    prime:
      - usr/lib/*/pipewire-*
      - usr/lib/*/spa-*
      - usr/lib/*/libpipewire*.so*
      - usr/lib/*/gstreamer-1.0/*.so
      - usr/share/pipewire

# should perhaps be in the sdk instead
  gstreamer:
    plugin: nil
    stage-packages:
      - gstreamer1.0-gl
    prime:
      - usr/lib/*/gstreamer-1.0/libgstopengl.so

  cleanup:
    after: [snapshot]
    plugin: nil
    build-snaps: [core22, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done

  snapshot:
    after: [ rustup ]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/snapshot.git
    source-tag: '45.0'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - gstreamer1.0-plugins-bad
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
    parse-info: [ usr/share/metainfo/org.gnome.Snapshot.metainfo.xml ]

slots:
  snapshot:
    interface: dbus
    bus: session
    name: org.gnome.Snapshot

apps:
  snapshot:
    command: usr/bin/snapshot
    desktop: usr/share/applications/org.gnome.Snapshot.desktop
    extensions: [ gnome ]
    common-id: org.gnome.Snapshot
    environment:
      GST_PRESET_PATH: "$SNAP/gnome-platform/usr/share/gstreamer-1.0/presets"
      PIPEWIRE_CONFIG_NAME: "$SNAP/usr/share/pipewire/pipewire.conf"
      PIPEWIRE_MODULE_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pipewire-0.3"
      SPA_PLUGIN_DIR: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/spa-0.2"
    plugs:
      - camera
      - audio-playback
      - audio-record
